
-- QUESTION1. What is the total revenue generated by male vs female customers?
select gender as Gender, sum(purchase_amount) AS Total_revenue
from mytable
group by gender;


-- QUESTION 2. Which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount as Total_spent
from mytable 
where discount_applied="yes" and purchase_amount>(select avg(purchase_amount)
from mytable);

-- QUESTION 3. What are the top 5 products with highest average review rating?
select item_purchased, ROUND(avg(review_rating),2) AS "Average product rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- QUESTION 4. Compare the average purchase amonut between strandard and express shipping ?
SELECT shipping_type, ROUND(avg(purchase_amount),2)
FROM mytable
WHERE shipping_type IN ("standard","express")
GROUP BY shipping_type;

-- QUESTION 5. Do subsribed customers spend more? compare average spend and total revenue between subsribed and non subsribed.
SELECT subscription_status, COUNT(customer_id), ROUND(AVG(purchase_amount),2) AS Average_spend, SUM(purchase_amount) AS Total_spend
FROM mytable
GROUP BY subscription_status;

-- QUESTION 6. Which 5 products have the highest percentage of purchase with discount applied?
SELECT item_purchased, ROUND(SUM(CASE WHEN discount_applied= "yes" THEN 1 ELSE 0 END)/COUNT(*)*100 ,2) AS dis
FROM mytable 
GROUP BY item_purchased
ORDER BY dis DESC
LIMIT 5;

-- QUESTION 7. Segment customers into new, returing and loyal based on their total number of privious purchases and show the
-- count of each segment?
WITH customer_type AS(
SELECT customer_id, case
WHEN previous_purchases = 1 THEN "New"
WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
ELSE "Loyal" END AS customer_segment
FROM mytable
)
SELECT customer_segment, COUNT(customer_id) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment;

-- QUESTION 8. What are the top 3 most purchased products with in each category?
WITH customers AS (
SELECT category, item_purchased, COUNT(*) AS total_orders, ROW_NUMBER() OVER( PARTITION BY category ORDER BY COUNT(*)) AS item_rank
FROM mytable
GROUP BY category, item_purchased
)
SELECT category, item_purchased, item_rank, total_orders
FROM customers
WHERE item_rank <=3;

-- QUESTION 9. are custmers who are repeat buyers (more than 5 privious purchase) also like to subscribe?
SELECT subscription_status, COUNT(customer_id)
FROM mytable
WHERE previous_purchases >5
GROUP BY subscription_status;

-- QUESTION 10. What are the revenue contribution in each age group?
SELECT  age_group, SUM(purchase_amount)
FROM mytable
GROUP BY age_group;